#eureka:
#  instance:
#    instance-id: config
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost1:7000/eureka,http://localhost2:7001/eureka,http://localhost3:7002/eureka
server:
  port: 9527
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    config:
      server:
        git:
          uri: https://github.com/liaozhiwei1/springConfig.git
          username: liaozhiwei1
          password: liao19961229
      label: master
  application:
    name: config
  rabbitmq:
    host: 10.88.27.189
    username: admin
    password: admin
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "*"