#eureka:
#  instance:
#    instance-id: gateway
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost1:7000/eureka,http://localhost2:7001/eureka,http://localhost3:7002/eureka
server:
  port: 9527
spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: consumer
#          uri: http://127.0.0.1:8080
#          predicates:
#            - Path= /test/**
#
#        - id: consumer
#          uri: http://127.0.0.1:8080
#          predicates:
#            - Path= /hytrix/**