eureka:
  instance:
    instance-id: consumer
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost1:7000/eureka,http://localhost2:7001/eureka,http://localhost3:7002/eureka
server:
  port: 8080
spring:
  application:
    name: consumer
#ribbon:
#  ConnectTimeout: 2000
#  ReadTimeout: 2000
logging:
  level:
    com.lzw.consumer.feign.Feign: debug