server:
  port: 7002
eureka:
  instance:
    hostname: localhost3
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost2:7001/eureka,http://localhost1:7000/eureka
