server:
  port: 7000
eureka:
  instance: localhost1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost2:7001/eureka,http://localhost3:7002/eureka
